name: api-build

on:
  push:
    paths:
    # limiting push to a subset of paths
    # to this .yml file
    # and under the api directory - meaning the source code of this application
      - ".github/workflows/api-build.yml"
      - "api/**"
  workflow_dispatch: # manual

jobs:
  build:
    name: build-dotnet-api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: ./api
      



# *** notes:
# steps[*].working-directory: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsworking-directory
# path filter globs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
