name: upper-build-me

on:
  push:
    paths:
      - ".github/workflows/upper-build-me.yml"
      - "upper/**"
  workflow_dispatch: # manual

jobs:
  build:
    name: build-go-app
    runs-on: ubuntu-latest
    steps:
      # pwd -> printout the current directory
      # ls -al -> list out all files
      - run: pwd && ls -al
      - uses: actions/checkout@v4
      - run: pwd && ls -al
      - run: go version
      - run: | # to add an inline multi-line script
          ls
          go build
          ls
          go test
          ./upper foo the bar
        working-directory: upper
        name: build and test